### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_86#1]
- [x] wykonaj poprawki analogiczne do poprzedniego zadania (wciecia, gitignore)
- [x] obecnie nie mozesz byc na 100% pewny, ze w ostatnim `else` bedzie wynik rowny zero. Sprobuj wpisac jako a i b litery zamiast liczb. 
Proponuje Ci rozwinac zadanie sprawdzajac, czy wartosc faktycznie jest rowna zero, oraz dodac ostatni else, ktory bedzie wypisywal informacje, ze "wynik jest nieokreslony"

**Comment by nescomtm** [comment]
zrobione jeszcze wczoraj

**Comment by nescomtm** [comment]
wciecia zrobione
a .gitignore jest u mnie w katalogu , tez mam go wysłać na gita ?

**Comment by nescomtm** [comment]
plik .gitignore dodant
